# Generated by Django 5.0.1 on 2024-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
